package pl.jaczewski.GtN;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.event.ContextRefreshedEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;
import pl.jaczewski.GtN.game.Game;
import pl.jaczewski.GtN.messages.MessageGenerator;

import java.util.Scanner;

@Component
public class Console {

    private final Game game;
    private final MessageGenerator messageGenerator;

    @Autowired
    public Console(Game game, MessageGenerator messageGenerator) {
        this.game = game;
        this.messageGenerator = messageGenerator;
    }

    @EventListener(ContextRefreshedEvent.class)
    public void startTheGame() {
        System.out.println(intro());

        Scanner sc = new Scanner(System.in);

        while (true) {
            System.out.println(messageGenerator.getMainMessage());
            System.out.println(messageGenerator.getResultMessage());

            System.out.print("Guess: ");
            while (!sc.hasNextInt()) {
                System.out.println("Sorry, only integers allowed!");
                System.out.print("Guess: ");
                sc.next();
            }
            int playerGuess = sc.nextInt();
            sc.nextLine();
            game.setPlayerGuess(playerGuess);
            game.check();

            if (game.isGameWon() || game.isGameLost()) {
                System.out.println(messageGenerator.getResultMessage());
                System.out.println("Play again? y/n");

                String decision = sc.nextLine().trim();
                if (!decision.equalsIgnoreCase("y") && !decision.equalsIgnoreCase("yes")) {
                    System.out.println(outro());
                    break;
                }
                game.resetGame();
            }
        }
    }

    private String intro() {
        return "\n" +
               "**************************************************************************************\n" +
               "----------------------- Welcome to the Guess the Number Game! ------------------------\n" +
               "--------- Your goal is to find a random number generated by this application ---------\n" +
               "You can adjust the default settings in the 'game.properties' file (in 'resources' dir)\n" +
               "-------------------------------------- Have fun! -------------------------------------\n" +
               "**************************************************************************************\n";
    }

    private String outro() {
        return "\n" +
                "**************************************************************************************\n" +
                "-------------------------------- Thank you for playing! ------------------------------\n" +
                "------------------------------- Hope you enjoyed it :-) ------------------------------\n" +
                "**************************************************************************************\n";
    }
}
